keys:
  # nixos-laptop host key
  - &host-nixos-laptop age1wvrflc26s33z8regje0sc599s8qlakx4pd8c45905r8g2mghqv5s2qq8d8
creation_rules:
  - path_regex: ^secrets/secrets\.yaml$
    age: [*host-nixos-laptop]
