keys:
  # nixos-laptop host key
  - &host-nixos-laptop age1wvrflc26s33z8regje0sc599s8qlakx4pd8c45905r8g2mghqv5s2qq8d8
  # user key (frank) - enables editing secrets without sudo
  - &user-frank age17huf4n5tvf09sazcvdz66h70ecwey26fqjzv99dwrdx0wpx934fq602ne9
creation_rules:
  - path_regex: ^secrets/secrets\.yaml$
    age: [*host-nixos-laptop, *user-frank]
