# Stateless root: everything on the tmpfs / is wiped every reboot; only state
# declared below survives, bind-mounted from the LUKS partition at /nix/persist
# (the `environment.persistence` root). The nix store itself is already
# persistent on the /nix partition, so nothing here touches /nix/store.
#
# Rule of thumb for adding entries: persist anything that must survive a
# reboot but is not regenerated by Nix (declarative home-manager configs and
# systemd tmpfiles regenerate themselves). Cache and thumbnails belong on
# tmpfs, not here.

{ user, ... }:

{
  environment.persistence."/nix/persist" = {
    hideMounts = true;

    directories = [
      "/var/lib/bluetooth"
      "/var/lib/libvirt"
      "/var/lib/NetworkManager"
      "/var/lib/nixos"
      "/var/log"
    ];

    files = [
      "/etc/machine-id"
      # Dedicated sops age key (modules/nixos/tools/sops.nix); install.sh
      # stages it into /nix/persist/etc/sops-nix/keys.txt, so the bind mount
      # is populated on first boot.
      "/etc/sops-nix/keys.txt"
      # SSH host identity: stable across reboots and reinstalls. install.sh
      # stages both halves into /nix/persist/etc/ssh.
      "/etc/ssh/ssh_host_ed25519_key"
      "/etc/ssh/ssh_host_ed25519_key.pub"
      # git safe.directory for root (install.sh stages it into persist).
      "/root/.gitconfig"
    ];

    users.${user} = {
      directories = [
        "Backups"
        "Documents"
        "Downloads"
        "Projects"
        # User age key for interactive sops edits (docs/secrets.md); not
        # regenerated by Nix.
        ".config/sops/age"
        # Wallpaper pick state; waypaper --restore re-applies it at boot.
        ".config/waypaper"
        # gnome-keyring store (modules/nixos/system/keyring.nix).
        ".local/share/keyrings"
        # opencode auth + session state (provider tokens, conversations).
        ".local/share/opencode"
        # SSH client / git-signing keys.
        ".ssh"
        # The `.config/opencode|restic|github` dirs are NOT persisted: sops-nix
        # regenerates those API tokens every boot.
      ];
      files = [
        # Shell history (zsh); HISTFILE lives here.
        ".zsh_history"
      ];
    };
  };
}
